services:
  - type: web
    name: pothole-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
